services:
  database:
    image: mariadb:11.4
    container_name: mariadb
    environment:
      MARIADB_DATABASE: news-adpc-69
      MARIADB_USER: news-adpc-69
      MARIADB_PASSWORD: B8gt5k98c!
    volumes:
      - ./data/db:/var/lib/mysql
