services:
  database:
    image: mariadb:11.4
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: B8gt5k98c!
      MARIADB_DATABASE: news-adpc-69
      MARIADB_USER: news-adpc-69
      MARIADB_PASSWORD: B8gt5k98c!
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
  webserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www/html
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "8085:80"
  php:
    image: php:8.4-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
